### ISSUE TITLE
Add description to commit types

### ISSUE THREAD

**Issue by JockeRider199** [Everduin94/better-commits#10]
How about adding a simple description next to commit types, such as the Angular convention:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/40937306/225004153-7c7d7772-e323-4c3c-9c62-d08ea67d72bc.png">

And simply adding those here
<img width="663" alt="image" src="https://user-images.githubusercontent.com/40937306/225003985-ef81e064-49f5-40b4-a608-7ec2efe44b44.png">

I always struggle to choose the right one and end up opening my browser to find which is for what

**Comment by Everduin94** [comment]
This is already possible by adding `hint` to each item in your config. Do you mean add it to the defaults?

https://user-images.githubusercontent.com/14320878/225009425-acabe9d0-336f-461b-848e-765524be629a.mov

**Comment by AlexHodson** [comment]
I think having the hints added by default would be useful

**Comment by JockeRider199** [comment]
> Do you mean add it to the defaults?

Yes, that was what I meant. Adding those hints by default and being able to override them would be convenient

**Comment by Everduin94** [comment]
Sure thing. Done. -- Although, you'll probably need to update your config. I haven't settled on a good way of handling this yet.

Few manual options:
- global config: you can delete the config and it will regenerate. Or copy paste the defaults from the readme.
- repository config: run `better-commits-init` or copy paste
- If the property is not present, it will just use the defaults (see the config in this repository). So you could just remove from your config what you want to be defaulted.
