### ISSUE TITLE
Default "max_items" value set to null

### ISSUE THREAD

**Issue by AlexHodson** [Everduin94/better-commits#107]
Just tried to install on a new machine and when I first run the "better-commits" command. The following response was given:

Found global config
│
■  Invalid Configuration: commit_type.max_items
│  Invalid type: Expected number but received null

I've had a look into the base global configuration file and for both `commit_type.max_items` & `commit_scope.max_items` are both set to null by default. Tried inputting the default configuration provided in the README, but the compains about "Infinity". Only way I can resolve this is to hardcode the max_items property to a specific number.

**Comment by Everduin94** [comment]
@AlexHodson - Thanks for catching / reporting this!

I didn't test defaults on a PR someone submitted. I goofed 🤦. Infinity on number never works with Valibot and the prop didn't have a min number validator either.
