### ISSUE TITLE
Compatible with overcommit 

### ISSUE THREAD

**Issue by harssh** [Everduin94/better-commits#14]
First, thank you for this fantastic tool.

Just checking if there is a way to make it work with https://github.com/sds/overcommit

I tried twice but it's not evoking overcommit.

**Comment by Everduin94** [comment]
I've never used overcommit, looking at the docs (I'm assuming this is a pre-commit hook), I believe it is anticipating `git commit`.

Can you try this as a test for me? -- Run `git commit -m "message" -e`.  Does that fire the overcommit hook?

If so, I believe there is a change I can try. If not, I don't think it's going to work.

**Comment by Everduin94** [comment]
Oh also

Does overcommit run if you simply run `git commit -m "message"` without `-e`?

**Comment by harssh** [comment]
Getting below output 

>  git commit -m "message" -e 
Running pre-commit hooks
Analyze with RailsBestPractices..................[RailsBestPractices] OK
Analyze with RuboCop........................................[RuboCop] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
Inspecting 1 file
C


But with better-commit it just silently fails to commit if there are offenses.

**Comment by Everduin94** [comment]
@harssh -- I created `1.0.8-print-output`. -- Its also the latest release so if you just update you should get the changes. Could you install and test it for me?

**Comment by harssh** [comment]
@Everduin94  Yes working now. 

Awesome.
