### ISSUE TITLE
AI Commits

### ISSUE THREAD

**Issue by dinhdjj** [Everduin94/better-commits#19]
Can you integrate AI to auto-generate a part of better-commits

For example: https://github.com/Nutlope/aicommits

**Comment by Everduin94** [comment]
Would be a cool idea, but I will probably not implement it. -- At best, I may add flags to pre-populate better-commits (for example `--title="your ai generated commit"` so you could dry run something like aicommits and pipe it to this tool

Also, using aicommits as an example of integrating ai (directly)

aicommits
- (indirectly) costs money
- requires a network connection
- is 10x the install size of better-commits
- has legal considerations (for example, I can't use chat-gpt for programming at my work)

i.e. I'd prefer to spend my time making the tool lighter, faster, and simple. While keeping it free and accessible to everyone.
