### ISSUE TITLE
Config Explanation Table (Readme)

### ISSUE THREAD

**Issue by Everduin94** [Everduin94/better-commits#26]
A table should be added to the Readme that explains what each property does

This would be a good first time issue / help wanted

I can fill in any gaps or help with any explanations if someone else ends up picking this up

**Comment by bhanudatsinhjhala** [comment]
Can you please assign me?

**Comment by Everduin94** [comment]
@bhanudatsinhjhala - Hey sorry for the late reply, I was on vacation :)

You can fork and give it a shot,  there's no official rules here about assigning haha. Thanks for wanting to contribute, I appreciate it :)

To add more context, I'm thinking the table should be something like this.

| Property |  Description |
| --------- | ------------ |
| property-name-here | a short description of what it does |

If the property name is nested in an object like `commit_type: { enable }` then write it like this as the property name: `commit_type.enable`.

Does that all make sense? -- Even if you're not sure what something does, just building out the structure of the table for me to fill in would be very helpful.
