### ISSUE TITLE
CI and Semantic Release

### ISSUE THREAD

**Issue by Everduin94** [Everduin94/better-commits#27]
Currently, better-commits process for deploying looks like this:
- manually bump version number in `package.json`
- manually build via `npm run build`
- manually publish via `npm publish`

Utilizing Github Actions + Semantic Release, we could automate this process. Which would make accepting other user's PRs simpler.

This would be a good first time issue / help wanted -- as I won't be able to get to this for a while

**Comment by AlexHodson** [comment]
This is probably something I could look into, but it won't be for a few weeks. If the issue is still on here then, I'll take it up.

**Comment by Woofenator** [comment]
I'll take this one. Should have something actionable in a few days
