### ISSUE TITLE
Semantic Release Support for Gitmojis (Internal)

### ISSUE THREAD

**Issue by Everduin94** [Everduin94/better-commits#39]
Better Commits has the git emoji configuration enabled. 

However, semantic release is not setup to recognize this.

Thus, a commit such as: ✨ feat(something): my commit -- runs a successful build, but doesn't tag/deploy a new version.

Add plugin: https://github.com/momocow/semantic-release-gitmoji ?

**Comment by bhanudatsinhjhala** [comment]
Is this issue still there? @Everduin94

**Comment by Everduin94** [comment]
@bhanudatsinhjhala - Yes it is still open :)

Also when I get the chance I will take a look at your PR. Just busy with work atm.

**Comment by bhanudatsinhjhala** [comment]
This is what I understand correct me if I understand it wrong, I have to integrate semantic-release package to get the emoji in the git right?

**Comment by Everduin94** [comment]
Closing issue, purely cosmetic and would rather focus on higher impact issues.
