### ISSUE TITLE
commit title keeps refusing characters saying "Exceed max length. Title max [70]"

### ISSUE THREAD

**Issue by Tchakoumi** [Everduin94/better-commits#48]
![image](https://github.com/Everduin94/better-commits/assets/43315117/3faa21da-7b41-4283-962c-184f7db41443)

**Comment by Everduin94** [comment]
Max title length takes things like scope/type/ticket into consideration 

What are you adding to the previous prompts? I can only see the warning in the screenshot

**Comment by Tchakoumi** [comment]
oh, I see, the ticket titles where quite long.
in this case, is it not ideal to increase the max length from 70 to about a hundred? or add a limit to the titcket permitting to write a better commit title?

**Comment by Everduin94** [comment]
@Tchakoumi you can already do this :) -- see `commit_title.max_size` in your config.

It's 70 because 70 is the PR title limit on github. Anything larger than 70 on a github PR gets moved to the body.

**Comment by Tchakoumi** [comment]
ahn ok, thank you.

**Comment by Tchakoumi** [comment]
How can I learn this terminal building?
I'd like to contribute to this project. it's very interesting. 

Any resources please?

**Comment by Everduin94** [comment]
Good question. 

I'm currently traveling and posting on my phone so I don't have links

But this specifically uses nodejs / typescript. -- so you could look up any articles videos on building terminal applications with typescript. 

It's very similar to building any other app with a few differences

My discord username is `boogersllc` you could message me there with any questions and I can try to get back to you when I'm back from traveling :)
