### ISSUE TITLE
How break a line in detailed description of the chages session

### ISSUE THREAD

**Issue by Wh-Marc** [Everduin94/better-commits#59]
I can't find the way to write multi line in  **detailed description of the chages** session

![image](https://github.com/Everduin94/better-commits/assets/122012490/ec18652f-9cc5-4f9a-94e4-54999ff1447b)

**Comment by Wh-Marc** [comment]
tried to mark with label but it seems I can't select label

**Comment by Everduin94** [comment]
Unfortunately, you have to use a `\n` character to make a new line.

The upstream library that controls the prompts doesn't support multi-line https://github.com/natemoo-re/clack/issues/25

And it looks like they're not accepting / merging PRs :( https://github.com/natemoo-re/clack/pull/143

**Comment by Everduin94** [comment]
@reggermont - No worries! I took a look at the PR I originally linked. Just at a glance (and with my limited knowledge of *clack*), not personally a PR I would merge.

The PR is doing a lot more than just adding multi-line support. And blocks of code like this are concerning **imo**. [Example](https://github.com/natemoo-re/clack/pull/143/files#diff-b315e5247cbc49265ece7c784fbcd4d90423a23cc64500338a5aef00b2ba83f6R371-R381)

We really just need the ability to start a new line when pressing enter, and continuing on something like ctrl-enter. - Forking clack, merging that PR, and maintaining our forked version is a relatively huge amount of effort given the scope of how small better-commits is.
