### ISSUE TITLE
Branch Template Property

### ISSUE THREAD

**Issue by Everduin94** [Everduin94/better-commits#71]
## Context

Based on https://github.com/Everduin94/better-commits/discussions/68 (@groovyghoul)

Today, although each part is optional, the order in the branch name when running `better-branch` is fixed.

`USER/TYPE/TICKET-DESCRIPTION`

## Tasks

Create a property `branch_template`
- Default: `user/type/ticket-description`

Zod Validation
- Enforce key words: ["user", "type", "ticket", "description", "version"]
- Enforce separators: ["/", "-", "_"]

Regex
- Update builder to use template
- See #70 make sure to not break inference between these two changes

Add either
- A way to make custom fields / prompts
- **Optional version number field** (leaning towards this for now)

### Outstanding Tasks
- This will effectively make fields like `optional` or `separator` redundant in some cases. Should we deprecate?

**Comment by groovyghoul** [comment]
@Everduin94 I finally got a chance to install and configure. This is working EXACTLY how I want it! Thanks for going above and beyond.
