### ISSUE TITLE
Request for Feature to Customize Ticket Format in Commit Messages

### ISSUE THREAD

**Issue by shiw-yang** [Everduin94/better-commits#72]
Hello,

I'm a developer working with a team where we follow a specific commit message convention: `type(scope): [jira_id] Commit_title.` We are interested in using the better-commits tool to streamline our development process. However, we have encountered an issue that better-commits does not seem to support customizing the ticket format in the check_ticket configuration, particularly adding brackets around the ticket ID.

Our team's convention requires the JIRA ticket ID to be enclosed in square brackets (`[jira_id]`), which is a crucial part of our workflow. Currently, the better-commits tool allows adding a ticket to the title but does not support this specific format.

I would like to inquire if there is any consideration for introducing a feature that allows customizing the ticket format, particularly for adding brackets around the ticket ID. If there's an interest in supporting this feature, I would be very eager to contribute to the project, ideally starting in early February.

Thank you for your time and consideration, and I look forward to any guidance or suggestions you may have on this matter.

**Comment by Everduin94** [comment]
Hey thanks for taking the time to write this up!

We have an issue: #70 that should solve this (and other problems like it). 

That ticket might take me a while to get to that since it's a noticeable paradigm shift in how the title would be built (and I'm currently on paternity leave). - Alternatively, and I'm not 100% on this direction. But, I may just add another property to `check_ticket` to add a wrapper such as `()` or `[]` or `{}`.

**Comment by shiw-yang** [comment]
> Hey thanks for taking the time to write this up!
> 
> We have an issue: #70 that should solve this (and other problems like it).
> 
> That ticket might take me a while to get to that since it's a noticeable paradigm shift in how the title would be built (and I'm currently on paternity leave). - Alternatively, and I'm not 100% on this direction. But, I may just add another property to `check_ticket` to add a wrapper such as `()` or `[]` or `{}`.

Thank you so much for responding to my query, and I apologize for missing the earlier issue.

I find the design in your issue incredibly well-thought-out and perfectly suited to meet our needs while offering great flexibility. I really appreciate and like this approach.

I plan to attempt an implementation based on your concept in early February. However, I might not achieve a perfect result since I primarily work with Go and have only recently started learning TypeScript as a hobby. If there are quicker or better implementations, please feel free to merge others' code.

Finally, congratulations on becoming a father, and I wish your family happiness and fulfillment.
