### ISSUE TITLE
Allow `$EDITOR` to display final confirmation

### ISSUE THREAD

**Issue by AlexAxthelm** [Everduin94/better-commits#82]
It would be nice if I could use my normal `$EDITOR` to see (or touch up) my commit message, rather than displaying it in-line for the final confirmation step.

**Comment by Everduin94** [comment]
Makes sense! I added this in PR: #83. 

You may have to explicitly set the editor via `git config`. I put some examples in the README. 

I'll probably merge this tomorrow after I get the chance to test one more thing.

**Comment by AlexAxthelm** [comment]
Looks to be working perfectly!
