### ISSUE TITLE
Reporting Security Vulnerability

### ISSUE THREAD

**Issue by dwisiswant0** [Everduin94/better-commits#86]
Hi @Everduin94,

As there is currently no [`SECURITY.md`](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) policy in place, could you please [activate private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository) for this repo to facilitate coordinated vulnerability disclosure?

Thank you.

**Comment by Everduin94** [comment]
Sure thing! - Enabled. 

<img width="792" alt="image" src="https://github.com/Everduin94/better-commits/assets/14320878/602d7f11-a84a-4378-be2e-6eca28b4f45b">
